services:
  react-design-systems-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/agentience/react-design-systems-mcp:latest
    container_name: react-design-systems-mcp
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - BIND=0.0.0.0
    restart: unless-stopped