name: React Design Systems MCP Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json, using npm ci"
            npm ci
          else
            echo "No package-lock.json found, using npm install"
            npm install
          fi
      - run: npm run test:ci
      - run: npm run build
      # The postbuild script already makes dist/server.js executable
      # Ensure the server file is executable
      - name: Make server file executable
        run: chmod +x dist/server.js
      
      # Check if package name is scoped (starts with @)
      - name: Check if package is scoped
        id: package-check
        run: |
          IS_SCOPED=$(node -e "const pkg = require('./package.json'); console.log(pkg.name.startsWith('@') ? 'true' : 'false');")
          echo "IS_SCOPED=$IS_SCOPED" >> $GITHUB_ENV
          echo "Package name from package.json: $(node -e "console.error(require('./package.json').name)")"
      
      # Publish package to NPM registry
      - name: Publish package to NPM
        run: |
          if [ "$IS_SCOPED" = "true" ]; then
            echo "Publishing scoped package with --access public"
            npm publish --access public
          else
            echo "Publishing regular package"
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
